dotnet/blazor-samples

README.md
Change `razor` to `cshtml` since razor is not in the list of languages for samples. This is causing an error that prevents listing in the Docs / Samples browser.
=> Fix sample frontmatter

7.0/BlazorSample_Server/Shared/data-binding/NestedChild.razor, 7.0/BlazorSample_WebAssembly/Shared/data-binding/NestedChild.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/26364
=> Update cross-component binding example

CODE-OF-CONDUCT.md
Fixes https://github.com/dotnet/org-policy-violations/issues/4988
I was following https://github.com/dotnet/AspNetCore.Docs.Samples/pull/139, which is apparently incorrect.
I'm reverting back to what I had.
=> Revert code of conduct updates

8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs
Per https://github.com/dotnet/AspNetCore.Docs/issues/31205#issuecomment-1841385405 ...
> This prevents the endpoint from accepting any forms posts. I spoke with our security team, and they indicated JSON-only endpoints that don't accept form auth or form posts don't need XSRF protections (which is why the `MapIdentityEndpoints` don't use anti-XSRF). The only way the /logout endpoint above works is if you post a JSON payload of `{}` which becomes an empty object with no properties but is not null. AFAIK this can't be done from a form.
=> Update Identity+WASM sample

8.0/BlazorSample_BlazorWebApp/BlazorSample.csproj, 8.0/BlazorSample_BlazorWebApp/Components/Pages/Daleks.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/EmptyContent.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter1.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter2.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/PromotionGrid.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/VirtualizedTable.razor, 8.0/BlazorSample_BlazorWebApp/Dalek.cs, 8.0/BlazorSample_BlazorWebApp/Program.cs, 8.0/BlazorSample_BlazorWebApp/WeatherForecastService.cs, 8.0/BlazorSample_WebAssembly/BlazorSample.csproj, 8.0/BlazorSample_WebAssembly/Dalek.cs, 8.0/BlazorSample_WebAssembly/Pages/Daleks.razor, 8.0/BlazorSample_WebAssembly/Pages/EmptyContent.razor, 8.0/BlazorSample_WebAssembly/Pages/PromotionGrid.razor, 8.0/BlazorSample_WebAssembly/Pages/VirtualizedTable.razor, 8.0/BlazorSample_WebAssembly/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31029
=> Move examples to sample apps

8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
[EDIT by guardrex to add another 'fixes']
Fixes issue `dotnet/AspNetCore.Docs` [#31205](https://github.com/dotnet/AspNetCore.Docs/issues/31205)
Fixes #132
=> Check for (and send) empty body on log out post.

3.1/BlazorSample_Server/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 3.1/BlazorSample_WebAssembly/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 5.0/BlazorSample_Server/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 5.0/BlazorSample_WebAssembly/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 6.0/BlazorSample_Server/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 6.0/BlazorSample_WebAssembly/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 7.0/BlazorSample_Server/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 7.0/BlazorSample_WebAssembly/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs, 8.0/BlazorSample_BlazorWebApp/DetectIncorrectUsagesOfTransientDisposables.cs, 8.0/BlazorSample_WebAssembly/DetectIncorrectUsagesOfTransientDisposables.cs
The `CreatePatchedDescriptor()` and `CreatePatchedFactoryDescriptor()` methods both create a new descriptor based on the original descriptor. However, it's unclear why `CreatePatchedDescriptor` method hardcodes `ServiceLifetime.Transient`, whereas `CreatePatchedFactoryDescriptor` uses `original.Lifetime` for the same intended outcome.
I believe the example implementation should avoid raising such questions among readers, and thus I recommend using a consistent approach in both methods.
=> DetectIncorrectUsagesOfTransientDisposables - implementation alignment

3.1/BlazorSample_Server/Services/TransitiveTransientDisposableDependency.cs, 3.1/BlazorSample_Server/Startup.cs, 5.0/BlazorSample_Server/Services/TransitiveTransientDisposableDependency.cs, 5.0/BlazorSample_Server/Startup.cs, 6.0/BlazorSample_Server/Program.cs, 6.0/BlazorSample_Server/Services/TransitiveTransientDisposableDependency.cs, 7.0/BlazorSample_Server/Program.cs, 7.0/BlazorSample_Server/Services/TransitiveTransientDisposableDependency.cs
Moving the transient disposables code in <8.0 samps to a `Services` folder with a new namespace. This is to match the 8.0 sample and make the article text clean on the location of the file.
=> Move transient disposables code

8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs, 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/SeedData.cs, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Layout/NavMenu.razor, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/PrivateEditorPage.razor, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/PrivateManagerPage.razor, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31045
Probably a fancier and more performant way to do this 🙈, but here's something to get us rolling at least for discussion.
Everything I show below is on the PR and ✨ ***Just Works!***&trade; ✨.
First of all, I think it's a good idea to have seeded data for learning and testing with role claims, ***AND*** I loathe having to re-register a test user over and over ... ***and over*** 😠. I place a `SeedData` class in here to take care of both. It creates a user, Bob 🤠, with two role claims (`Administrator`, `Manager`). We'll get seeded right after the app is built ...
```csharp
#if DEBUG
using (var scope = app.Services.CreateScope())
{
var services = scope.ServiceProvider;
SeedData.Initialize(services);
}
#endif
```
`IdentityUser` …
=> Add roles to WASM+Identity sample app

3.1/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor, 3.1/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor, 5.0/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor, 5.0/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor, 6.0/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor, 6.0/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor, 7.0/BlazorSample_Server/Pages/handle-errors/ProductDetails.razor, 7.0/BlazorSample_WebAssembly/Pages/handle-errors/ProductDetails.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/ProductDetails.razor, 8.0/BlazorSample_WebAssembly/Pages/ProductDetails.razor
Fixes #188
Look good, @hakenr? ... I'd like to leave the code comment in place on this one. I usually prefer to manage this in the article text because code comments aren't localized. However, this is a minor point that I'd prefer not to call out in the text in this case. I added a bit of padding around it as well. It presents well in the article this way.
=> Reset details to null

7.0/BlazorSample_Server/Pages/dependency-injection/TransientService.razor
The `7.0\BlazorSample_Server` was still not buildable.
Adding missing `using` to `TransientService.razor`
cc @guardrex
=> FIx build (net7 TransientService.razor)

6.0/BlazorSample_Server/lifecycle/WeatherForecastService.cs, 7.0/BlazorSample_Server/lifecycle/WeatherForecastService.cs, 8.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter1.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter2.razor, 8.0/BlazorSample_BlazorWebApp/WeatherForecastService.cs
.NET 6 introduced `Random.Shared` for scenarios where a specific seed value isn't required.
cc @guardrex
=> Random.Shared instead of new Random() (net6+)

6.0/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor, 6.0/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor, 7.0/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor, 7.0/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/Notifications.razor, 8.0/BlazorSample_WebAssembly/Pages/Notifications.razor
@guardrex, similar to our discussion on `DispatchExceptionAsync()`, the latest version of `TimerService.cs` (net6+) now uses `await timer.WaitForNextTickAsync()` within the asynchronous `Timer.Start()` method. This approach ensures all notifications are processed within the Blazor synchronization context (logical thread) when the Timer.Start is awaited from the button click event handler.
This setup means that `Notifications.razor` operates correctly even without utilizing the `InvokeAsync()` method.
To effectively illustrate the necessity for `InvokeAsync()`, we should execute the `Timer` outside the Blazor synchronization context (e.g. as a background service). This can be demonstrated by initiating it with `_ = Task.Run(() => Timer.Start())`. (It still functions without `InvokeAsync` …
=> Synchronization context sample - fire&forget for Timer.Start

3.1/BlazorSample_Server/Pages/overwriting-parameters/Expanders.razor, 3.1/BlazorSample_Server/Pages/overwriting-parameters/ExpandersToggle.razor, 3.1/BlazorSample_WebAssembly/Pages/overwriting-parameters/Expanders.razor, 3.1/BlazorSample_WebAssembly/Pages/overwriting-parameters/ExpandersToggle.razor, 5.0/BlazorSample_Server/Pages/overwriting-parameters/Expanders.razor, 5.0/BlazorSample_Server/Pages/overwriting-parameters/ExpandersToggle.razor, 5.0/BlazorSample_WebAssembly/Pages/overwriting-parameters/Expanders.razor, 5.0/BlazorSample_WebAssembly/Pages/overwriting-parameters/ExpandersToggle.razor
Fix for warnings found by the new CI build :-D
cc @guardrex
=> Expanders - no PageTitle component prior to net6

8.0/BlazorWebAppOidc/BlazorWebAppOidc/CookieOidcRefresher.cs, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/CookieOidcRefresher.cs
See https://security.stackexchange.com/questions/147529/openid-connect-nonce-replay-attack and https://github.com/IdentityServer/IdentityServer4/issues/2180 for the purpose of the nonce and why it's unnecessary for the token refresh.
This also switches to using `OpenIdConnectOptions.Backchannel` rather than its own `HttpClient` so it gets [an OIDC-specific user agent](https://github.com/dotnet/aspnetcore/blob/b3b8dffff4d092058b2d8942268b498cbfdb14ec/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectPostConfigureOptions.cs#L71) and includes any other customizations that might be necessary for communicating with the given OIDC provider.
Fixes https://github.com/dotnet/aspnetcore/issues/53585
=> Fix IDX21323: RequireNonce is 'False' during token refreshClient

8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/BlazorWebAppOidc.Client.csproj, 8.0/BlazorWebAppOidc/BlazorWebAppOidc/BlazorWebAppOidc.csproj, 8.0/BlazorWebAppOidcBff/Aspire/Aspire.AppHost/Aspire.AppHost.csproj, 8.0/BlazorWebAppOidcBff/Aspire/Aspire.ServiceDefaults/Aspire.ServiceDefaults.csproj, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/BlazorWebAppOidc.Client.csproj, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/BlazorWebAppOidc.csproj, 8.0/BlazorWebAppOidcBff/MinimalApiJwt/MinimalApiJwt.csproj, 8.0/BlazorWebAppOidcBff/README.md
Fixes #245
Thanks @cipherw0lf ... It's not clear from your issue if you configured everything properly to run, but I found several updates to make ...
* These had patch ASP.NET Core packages (8.0.1), but we normally just let the roll-forward patches take effect on their own. Therefore, I switched them to 8.0.0. Whatever the latest patch release, they will be consumed automatically.
* These projects had older preview and non-preview packages. I've updated those to the latest.
WRT the starting project, the guidance is correct in its present form. The solution should be started from the `Aspire/Aspire.AppHost` project.
=> BWAOidcBFF solution package updates

8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs, 8.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
Fixes #251
Thanks @swegele .... I didn't conclude that the `sts.windows.net` address for the authority was correct. I'm not sure how that figures into the general explanation. I thought that the authority should remain as Stephen Halter specified it here. What I do here is update the code comments to distinguish between the scope values for an ME-ID tenant versus an AAD B2C tenant. It looks like Halter was using a B2C tenant, and I'm familiar from other work with Azure on your use of an ME-ID tenant type (e.g., `api://{CLIENT ID}` App ID URI.
I'll take up changes to mirror these updates in the article next.
=> Add scope guidance based on tenant type

8.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
Fixes #251 
I'm definitely going to repro the whole setup ***BOTH*** ways ... with an AAD B2C tenant, which is what Halter was using, and an ME-ID tenant. For now, I'm just going to call this out here in the code comment and over on a different PR for the article.
=> Add remark on ME-ID authority in server API config

8.0/BlazorWebAppEFCore/Program.cs
For some reason, this call to AddDbContextFactory is inside a region (folded by default in some editors, e.g. VS2022)
Given that this is the only example for setting up this context factory (not included here: https://learn.microsoft.com/en-us/aspnet/core/blazor/blazor-ef-core?view=aspnetcore-8.0#sample-app), obscuring this seems like a bad idea. (Don't ask me how much time I just spent searching for where the factory was coming from...)
=> Remove pointless region from Program.cs

3.1/BlazorSample_Server/Shared/overwriting-parameters/BadShowMoreExpander.razor, 3.1/BlazorSample_Server/Shared/overwriting-parameters/ShowMoreExpander.razor, 3.1/BlazorSample_Server/Shared/overwriting-parameters/ToggleExpander.razor, 3.1/BlazorSample_WebAssembly/Shared/overwriting-parameters/BadShowMoreExpander.razor, 3.1/BlazorSample_WebAssembly/Shared/overwriting-parameters/ShowMoreExpander.razor, 3.1/BlazorSample_WebAssembly/Shared/overwriting-parameters/ToggleExpander.razor, 5.0/BlazorSample_Server/Shared/overwriting-parameters/BadShowMoreExpander.razor, 5.0/BlazorSample_Server/Shared/overwriting-parameters/ShowMoreExpander.razor, 5.0/BlazorSample_Server/Shared/overwriting-parameters/ToggleExpander.razor, 5.0/BlazorSample_WebAssembly/Shared/overwriting-parameters/BadShowMoreExpander.razor, 5.0/BlazorSample_WebAssembly/Shared/overwriting-parameters/ShowMoreExpander.razor, 5.0/BlazorSample_WebAssembly/Shared/overwriting-parameters/ToggleExpander.razor
build warnings
there were no nullable annotations in net5 & net31
feature downgrade for unsupported frameworks 😭
low prio
cc @guardrex
=> Expanders - nullable annotations removal in net5 & net31

.gitignore, 8.0/BlazorSample_BlazorWebApp/DetectIncorrectUsagesOfTransientDisposables.cs, 8.0/BlazorSample_WebAssembly/DetectIncorrectUsagesOfTransientDisposables.cs
The modification updates the conditional checks inside Transient Disposables service detection to include consideration for KeyedService. It now verifies whether a KeyedService exists, checking both ImplementationType and ImplementationFactory for each service offering, be it keyed or non-keyed.
Fixes https://github.com/dotnet/blazor-samples/issues/282
=> Improve handling of KeyedService in Transient Disposables detection

8.0/BlazorWebAppMovies/Data/SeedData.cs
Parsing a constant literal seems odd to me.
=> BlazorWebAppMovies/SeedData - DateOnly ctor instead of Parse()

8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32512
=> Update role claim type and remark

5.0/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample8.razor, 5.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor, 6.0/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample8.razor, 6.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor, 7.0/BlazorSample_Server/Pages/call-js-from-dotnet/CallJsExample8.razor, 7.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor, 8.0/BlazorSample_BlazorWebApp/Components/Pages/CallJs8.razor, 8.0/BlazorSample_WebAssembly/Pages/CallJs8.razor
I think the `.AsTask()` call doesn't add any value here (it would have been needed if there was a `return` instead of `await`).  
cc @guardrex
=> CallJsExample8.razor - AsTask() removed

8.0/BlazorSample_BlazorWebApp/Components/Pages/ShowFile.razor, 8.0/BlazorSample_WebAssembly/Pages/ShowFile.razor, 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor, 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/RedirectToLogin.razor, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor, 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/RedirectToLogin.razor, 9.0/BlazorSample_BlazorWebApp/Components/Pages/ShowFile.razor, 9.0/BlazorSample_WebAssembly/Pages/ShowFile.razor, 9.0/BlazorWebAppEntra/BlazorWebAppEntra.Client/Layout/LogInOrOut.razor, 9.0/BlazorWebAppEntra/BlazorWebAppEntra.Client/RedirectToLogin.razor, 9.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor, 9.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/RedirectToLogin.razor, 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Layout/LogInOrOut.razor, 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/RedirectToLogin.razor, 9.0/MauiBlazorWeb/MauiBlazorWeb.Web/Program.cs
"`Navigation`" consistency with articles, where using the shorter name helps with keeping code lines shorter.
=> NIT sample updates

8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs, 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/Models/RoleClaim.cs, 9.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs, 9.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/Models/RoleClaim.cs
=> Add logger and move RoleClaim class

BlazorWebAssemblyXrefGenerator/Pages/Home.razor, BlazorWebAssemblyXrefGenerator/wwwroot/css/app.css
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34461
=> Xref Gen tool updates

8.0/BlazorWebAppOidcServer/README.md, 9.0/BlazorWebAppOidcServer/README.md
For the work on https://github.com/dotnet/AspNetCore.Docs/issues/34605.
=> Cross-link updates

README.md
Hi Jon ... 👋 Hope ur well!!! ... and *Happy New Year!* 🍾
A few years ago, we had to remove `razor` from the code languages on https://github.com/dotnet/blazor-samples/pull/21. You said that you'd request it be added. Can we add `razor` back?
Also, it seems like the `urlFragment` should be `/` instead of `/blazor-samples` because the link to the sample browser ends up ...
```
https://learn.microsoft.com/en-us/samples/dotnet/blazor-samples/blazor-samples/
```
Let me know if that's going to break 💥, and I'll revert. 👂 
........ and ***one other ❓*** ... there's obviously a delay between when I update the README on this repo and when the MS samples page grabs that README's content for display. Do you know how long that delay is? ... just curious.
=> Add back 'razor' as a code language

9.0/BlazorWebAppWinAuthServer/Components/ForceLogin.razor, 9.0/BlazorWebAppWinAuthServer/Components/Layout/NavMenu.razor, 9.0/BlazorWebAppWinAuthServer/Components/Pages/LocalAccount.razor, 9.0/BlazorWebAppWinAuthServer/Components/Routes.razor, 9.0/BlazorWebAppWinAuthServer/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/34708#discussion_r1966360421
=> Update BWA WinAuth sample app

BlazorWebAssemblyXrefGenerator/Pages/Home.razor, BlazorWebAssemblyXrefGenerator/Program.cs
When trying out the Xref Generator I spotted the following things
* Clear button only cleared the search text, not the results on the screen
* When searching for an item with no results there was no message displayed
* When searching for an item with no results after getting previous results the previous results stayed on the screen
I had a peek through the code and made the following changes
* Updated the unused registered `APIBrowserPageClient` to `ProxyClient` to allow for use in code
* Only register `ProxyClient` once before using it to get each result
* `SearchResultItems?.Results` was never null from the first request so the `No results returned.` message was not getting displayed when searching for something with no results . This has been updated to `if …
=> Improvements to Xref Generator

BlazorWebAssemblyXrefGenerator/Pages/Home.razor, BlazorWebAssemblyXrefGenerator/Shared/ApiResult.razor
- Reduce duplication by taking a `RenderFragment` based approach
- Added a spinner to indicate when a search is still ongoing
- Switched margin styles to bootstrap classes
- Added a `MaxResults` constant to easily adjust if required
- Moved the secondary searches into the try-catch
- Tried to make the match logic for updating the link a little more readable
- Still return results to the UI as soon as they are available using `StateHasChanged`
- Removed now unrequired variable from the `ClearUI` method
=> Refactor xref-generator

9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs, 9.0/BlazorWebAppEntra/BlazorWebAppEntra/appsettings.json, 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs, 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/appsettings.json
Fixes #533
Per offline discussion, we're converting to C# configuration to help new-to-.NET devs with discovery of configuration settings via C# autocompletion. A new section will be added to the BWA+Entra article on how to configure the samples via the JSON config provider (app settings) on https://github.com/dotnet/AspNetCore.Docs/issues/35377.
=> Convert to C# configuration

9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Fixes #555
Thanks @lydia-gu! 🚀 
cc: @halter73 
I opened https://github.com/dotnet/AspNetCore.Docs/issues/35638 to make a remark about the use of the `https://weatherapi` destination prefix here.
=> Update BWA+Entra BFF sample
