- .gitignore
- 6.0/BlazorServerSignalRApp/Pages/Index.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/25584#issuecomment-1093317724
> Update BlazorServer-SignalR app

- 6.0/BlazorSample_Server/CustomFieldClassProvider.cs
- 6.0/BlazorSample_Server/CustomFieldClassProvider2.cs
- 6.0/BlazorSample_Server/CustomFieldClassProvider3.cs
- 6.0/BlazorSample_Server/CustomValidation.cs
- 6.0/BlazorSample_Server/JsInteropClasses1.cs
- 6.0/BlazorSample_Server/JsInteropClasses2.cs
- 6.0/BlazorSample_Server/JsInteropClasses3.cs
- 6.0/BlazorSample_Server/MessageUpdateInvokeHelper.cs
- 6.0/BlazorSample_Server/NotifierService.cs
- 6.0/BlazorSample_Server/Program.cs
- 6.0/BlazorSample_Server/Starship.cs
- 6.0/BlazorSample_Server/TrackingCircuitHandler.cs
- 6.0/BlazorSample_Server/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs
- 6.0/BlazorSample_Server/lifecycle/WeatherForecast.cs
- 6.0/BlazorSample_Server/lifecycle/WeatherForecastService.cs
- 6.0/BlazorSample_WebAssembly/CustomFieldClassProvider.cs
- 6.0/BlazorSample_WebAssembly/CustomFieldClassProvider2.cs
- 6.0/BlazorSample_WebAssembly/CustomFieldClassProvider3.cs
- 6.0/BlazorSample_WebAssembly/CustomValidation.cs
- 6.0/BlazorSample_WebAssembly/JsInteropClasses1.cs
- 6.0/BlazorSample_WebAssembly/JsInteropClasses2.cs
- 6.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
- 6.0/BlazorSample_WebAssembly/MessageUpdateInvokeHelper.cs
- 6.0/BlazorSample_WebAssembly/NotifierService.cs
- 6.0/BlazorSample_WebAssembly/Starship.cs
- 6.0/BlazorSample_WebAssembly/dependency-injection/DetectIncorrectUsagesOfTransientDisposables.cs
- 6.0/BlazorServerSignalRApp/Hubs/ChatHub.cs
- 6.0/BlazorWebAssemblySignalRApp/Server/Controllers/WeatherForecastController.cs
- 6.0/BlazorWebAssemblySignalRApp/Server/Hubs/ChatHub.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/25702
> Drop implicit namespaces

- 6.0/BlazorSample_Server/ComponentMetadata.cs
- 6.0/BlazorSample_Server/Pages/dynamiccomponent/DynamicComponentExample1.razor
- 6.0/BlazorSample_Server/Pages/dynamiccomponent/DynamicComponentExample2.razor
- 6.0/BlazorSample_Server/Pages/index/CounterPartialClass.razor.cs
- 6.0/BlazorSample_Server/Pages/index/ReceiveNotifications.razor
- 6.0/BlazorSample_Server/_Imports.razor
- 6.0/BlazorSample_WebAssembly/ComponentMetadata.cs
- 6.0/BlazorSample_WebAssembly/Pages/dynamiccomponent/DynamicComponentExample1.razor
- 6.0/BlazorSample_WebAssembly/Pages/dynamiccomponent/DynamicComponentExample2.razor
- 6.0/BlazorSample_WebAssembly/Pages/index/CounterPartialClass.razor.cs
- 6.0/BlazorSample_WebAssembly/Pages/index/ReceiveNotifications.razor
- 6.0/BlazorSample_WebAssembly/_Imports.razor
Fixes  #6
Thanks @yhan, @Stay1444, @kevison, and @agolks.
**_Sorry again for the delay!_** ... I only just saw the issue this morning (6/16/22) because I don't receive email pings when issues are opened on this repo. We normally work off of the `dotnet/AspNetCore.Docs` repo. When Blazor docs issues are opened there using the **This page** feedback form at the bottoms of our topics, I get the automatic email pings. I'll make a change to this samples repo to make sure that I get the email pings when issues are opened here.
> Update snippet samples

- 6.0/BlazorSample_Server/Pages/_Layout.cshtml
- 6.0/BlazorSample_WebAssembly/wwwroot/index.html
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/26298
> Fix file download JS FNs

- 6.0/BlazorSample_Server/DITopicClasses.cs
- 6.0/BlazorSample_Server/Pages/dependency-injection/Preferences.razor
- 6.0/BlazorSample_WebAssembly/DITopicClasses.cs
- 6.0/BlazorSample_WebAssembly/Pages/dependency-injection/Preferences.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/26385
> Remove hidden classes from DI example

- 3.1/BlazorSample_Server/DITopicClasses.cs
- 3.1/BlazorSample_WebAssembly/DITopicClasses.cs
- 5.0/BlazorSample_Server/DITopicClasses.cs
- 5.0/BlazorSample_WebAssembly/DITopicClasses.cs
Fixes #25
Thanks @jeffkenn2000! :rocket:
> Add namespace

- 7.0/BlazorSample_Server/JsInteropClasses3.cs
Async method is missing from function, small fix.
> adding missing async method

- 3.1/BlazorSample_Server/JsInteropClasses3.cs
- 3.1/BlazorSample_Server/wwwroot/css/open-iconic/README.md
- 3.1/BlazorSample_WebAssembly/JsInteropClasses3.cs
- 3.1/BlazorSample_WebAssembly/wwwroot/css/open-iconic/README.md
- 3.1/BlazorServerEFCoreSample/BlazorServerDbContextExample/wwwroot/css/open-iconic/README.md
- 5.0/BlazorSample_Server/JsInteropClasses3.cs
- 5.0/BlazorSample_Server/wwwroot/css/open-iconic/README.md
- 5.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
- 5.0/BlazorSample_WebAssembly/wwwroot/css/open-iconic/README.md
- 5.0/BlazorServerEFCoreSample/BlazorServerDbContextExample/wwwroot/css/open-iconic/README.md
- 6.0/BlazorSample_Server/JsInteropClasses3.cs
- 6.0/BlazorSample_Server/wwwroot/css/open-iconic/README.md
- 6.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
- 6.0/BlazorSample_WebAssembly/wwwroot/css/open-iconic/README.md
- 6.0/BlazorServerEFCoreSample/BlazorServerDbContextExample/wwwroot/css/open-iconic/README.md
- 6.0/BlazorServerSignalRApp/wwwroot/css/open-iconic/README.md
- 6.0/BlazorWebAssemblyScopesLogger/wwwroot/css/open-iconic/README.md
- 6.0/BlazorWebAssemblySignalRApp/Client/wwwroot/css/open-iconic/README.md
- 7.0/BlazorSample_Server/JsInteropClasses3.cs
- 7.0/BlazorSample_Server/wwwroot/css/open-iconic/README.md
- 7.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
- 7.0/BlazorSample_WebAssembly/wwwroot/css/open-iconic/README.md
- 7.0/BlazorServerEFCoreSample/wwwroot/css/open-iconic/README.md
- 7.0/BlazorServerSignalRApp/wwwroot/css/open-iconic/README.md
- 7.0/BlazorWebAssemblyScopesLogger/wwwroot/css/open-iconic/README.md
- 7.0/BlazorWebAssemblySignalRApp/Client/wwwroot/css/open-iconic/README.md
> Update samples for MIA async modifier and template changes

- 6.0/BlazorSample_Server/Shared/layouts/MainLayout.razor
- 6.0/BlazorSample_WebAssembly/Shared/MainLayout.razor
- 6.0/BlazorSample_WebAssembly/Shared/layouts/MainLayout.razor
- 7.0/BlazorSample_Server/Shared/layouts/MainLayout.razor
- 7.0/BlazorSample_WebAssembly/Shared/layouts/MainLayout.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/27515
> Layout updates

- 3.1/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 3.1/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 3.1/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem1.razor
- 3.1/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem2.razor
- 3.1/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 3.1/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 3.1/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem1.razor
- 3.1/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem2.razor
- 5.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 5.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 5.0/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem1.razor
- 5.0/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem2.razor
- 5.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 5.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 5.0/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem1.razor
- 5.0/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem2.razor
- 6.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 6.0/BlazorSample_Server/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 6.0/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem1.razor
- 6.0/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem2.razor
- 6.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample6.razor
- 6.0/BlazorSample_WebAssembly/Pages/call-dotnet-from-js/CallDotNetExample7.razor
- 6.0/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem1.razor
- 6.0/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem2.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/24615
> Backport JS interop example

- 3.1/BlazorSample_Server/Pages/index/PeopleExample.razor
- 3.1/BlazorSample_WebAssembly/Pages/index/PeopleExample.razor
- 5.0/BlazorSample_Server/Pages/index/PeopleExample.razor
- 5.0/BlazorSample_WebAssembly/Pages/index/PeopleExample.razor
- 6.0/BlazorSample_Server/Pages/index/PeopleExample.razor
- 6.0/BlazorSample_WebAssembly/Pages/index/PeopleExample.razor
- 7.0/BlazorSample_Server/Pages/index/PeopleExample.razor
- 7.0/BlazorSample_WebAssembly/Pages/index/PeopleExample.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/27703
> Rename People component

- 5.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 5.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 6.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 6.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 7.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 7.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
Fixes https://github.com/dotnet/AspNetCore.Docs/issues/27924
> Move code line in FileUpload2 component

- 3.1/BlazorSample_Server/MessageUpdateInvokeHelper.cs
- 3.1/BlazorSample_Server/Pages/_Host.cshtml
- 3.1/BlazorSample_WebAssembly/MessageUpdateInvokeHelper.cs
- 3.1/BlazorSample_WebAssembly/wwwroot/index.html
- 5.0/BlazorSample_Server/MessageUpdateInvokeHelper.cs
- 5.0/BlazorSample_Server/Pages/_Host.cshtml
- 5.0/BlazorSample_WebAssembly/MessageUpdateInvokeHelper.cs
- 5.0/BlazorSample_WebAssembly/wwwroot/index.html
- 6.0/BlazorSample_Server/MessageUpdateInvokeHelper.cs
- 6.0/BlazorSample_Server/Pages/_Layout.cshtml
- 6.0/BlazorSample_WebAssembly/MessageUpdateInvokeHelper.cs
- 6.0/BlazorSample_WebAssembly/wwwroot/index.html
- 7.0/BlazorSample_Server/MessageUpdateInvokeHelper.cs
- 7.0/BlazorSample_Server/Pages/_Host.cshtml
- 7.0/BlazorSample_WebAssembly/MessageUpdateInvokeHelper.cs
- 7.0/BlazorSample_WebAssembly/wwwroot/index.html
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/26980
> Update JS interop examples

- 5.0/BlazorSample_WebAssembly/JsInteropClasses1.cs
- 5.0/BlazorSample_WebAssembly/JsInteropClasses2.cs
- 5.0/BlazorSample_WebAssembly/JsInteropClasses3.cs
Missing using on these samples
> Missing using on these samples

- README.md
Contributes to https://github.com/dotnet/docs/issues/35970.
Matches action taken on https://github.com/dotnet/AspNetCore.Docs/pull/29647.
> Remove metadata

- 3.1/BlazorSample_Server/routing/App1.razor
- 3.1/BlazorSample_Server/routing/App2.razor
- 3.1/BlazorSample_Server/routing/Startup.cs
- 3.1/BlazorSample_WebAssembly/routing/App1.razor
- 3.1/BlazorSample_WebAssembly/routing/App2.razor
- 5.0/BlazorSample_Server/routing/App1.razor
- 5.0/BlazorSample_Server/routing/App2.razor
- 5.0/BlazorSample_Server/routing/Startup.cs
- 5.0/BlazorSample_WebAssembly/routing/App1.razor
- 5.0/BlazorSample_WebAssembly/routing/App2.razor
- 6.0/BlazorSample_Server/routing/App1.razor
- 6.0/BlazorSample_Server/routing/App2.razor
- 6.0/BlazorSample_WebAssembly/routing/App1.razor
- 6.0/BlazorSample_WebAssembly/routing/App2.razor
- 7.0/BlazorSample_Server/routing/App1.razor
- 7.0/BlazorSample_Server/routing/App2.razor
- 7.0/BlazorSample_WebAssembly/routing/App1.razor
- 7.0/BlazorSample_WebAssembly/routing/App2.razor
Reverts dotnet/blazor-samples#97
> Revert "Drop examples"

- .gitignore
- 7.0/BlazorSample_Server/Shared/SurveyPrompt.razor
- 7.0/BlazorSample_Server/_Imports.razor
Add Rider user folder to the gitignore
> Fixing build issues in the BlazorSample_Server 7.0 project. 

- 7.0/BlazorSample_Server/Shared/SurveyPrompt.razor.cs
I'm unsure if this works, but at least the example compiles.
> +IJSRuntime parameter

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/README.md
Improve this for .NET CLI users ... we want to make sure they run the projects security.
> Update WASM+Identity README

- 8.0/BlazorSample_BlazorWebApp/CustomFieldClassProvider.cs
- 8.0/BlazorSample_BlazorWebApp/CustomFieldClassProvider2.cs
- 8.0/BlazorSample_BlazorWebApp/CustomFieldClassProvider3.cs
- 8.0/BlazorSample_WebAssembly/CustomFieldClassProvider.cs
- 8.0/BlazorSample_WebAssembly/CustomFieldClassProvider2.cs
- 8.0/BlazorSample_WebAssembly/CustomFieldClassProvider3.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31311
> Refactor edit context code for new IsValid API

- 3.1/BlazorSample_Server/Pages/_Host.cshtml
- 3.1/BlazorSample_WebAssembly/wwwroot/index.html
- 5.0/BlazorSample_Server/Pages/_Host.cshtml
- 5.0/BlazorSample_WebAssembly/wwwroot/index.html
- 6.0/BlazorSample_Server/Pages/_Layout.cshtml
- 6.0/BlazorSample_WebAssembly/wwwroot/index.html
- 7.0/BlazorSample_Server/Pages/_Host.cshtml
- 7.0/BlazorSample_WebAssembly/wwwroot/index.html
- 8.0/BlazorSample_WebAssembly/wwwroot/index.html
Addresses https://github.com/dotnet/blazor-samples/pull/152
cc: @Rahul-K-Saini ... For future reference, all samples (usually) require the same update, and the article will be next over on the docs repo.
> Remove console logging

- 8.0/BlazorWebOidc/BlazorWebOidc.Client/Routes.razor
Fix for duplicate rendering issue in OIDC sample #144
> Remove extra RouteView from Routes.razor in OIDC sample

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Starship3.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Starship9.razor
- 8.0/BlazorSample_WebAssembly/Pages/Starship3.razor
- 8.0/BlazorSample_WebAssembly/Pages/Starship9.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31428
> Update select fields

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Backend.csproj
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs
> Remove Swashbuckle

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Backend.csproj
> Remove OpenAPI package

- 8.0/BlazorWebAppOidc/README.md
- 8.0/BlazorWebAppOidcBff/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31265
> BWA OIDC sample updates

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Layout/NavMenu.razor
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Layout/NavMenu.razor
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31265
> BWA+OIDC sample updates

- 3.1/BlazorSample_Server/Pages/dependency-injection/TransientService.razor
- 3.1/BlazorSample_Server/Startup.cs
- 3.1/BlazorSample_Server/dependency-injection/TransitiveTransientDisposableDependency.cs
- 3.1/BlazorSample_WebAssembly/Pages/dependency-injection/TransientService.razor
- 3.1/BlazorSample_WebAssembly/Program.cs
- 3.1/BlazorSample_WebAssembly/Services/TransientDisposableService.cs
- 5.0/BlazorSample_Server/Pages/dependency-injection/TransientService.razor
- 5.0/BlazorSample_Server/Startup.cs
- 5.0/BlazorSample_Server/dependency-injection/TransitiveTransientDisposableDependency.cs
- 5.0/BlazorSample_WebAssembly/Pages/dependency-injection/TransientService.razor
- 5.0/BlazorSample_WebAssembly/Program.cs
- 5.0/BlazorSample_WebAssembly/Services/TransientDisposableService.cs
- 6.0/BlazorSample_Server/Pages/dependency-injection/TransientService.razor
- 6.0/BlazorSample_Server/Program.cs
- 6.0/BlazorSample_Server/dependency-injection/TransitiveTransientDisposableDependency.cs
- 6.0/BlazorSample_WebAssembly/Pages/dependency-injection/TransientService.razor
- 6.0/BlazorSample_WebAssembly/Program.cs
- 6.0/BlazorSample_WebAssembly/Services/TransientDisposableService.cs
- 7.0/BlazorSample_Server/Pages/dependency-injection/TransientService.razor
- 7.0/BlazorSample_Server/Program.cs
- 7.0/BlazorSample_Server/dependency-injection/TransitiveTransientDisposableDependency.cs
- 7.0/BlazorSample_WebAssembly/Pages/dependency-injection/TransientService.razor
- 7.0/BlazorSample_WebAssembly/Program.cs
- 7.0/BlazorSample_WebAssembly/Services/TransientDisposableService.cs
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/TransientService.razor
- 8.0/BlazorSample_BlazorWebApp/Program.cs
- 8.0/BlazorSample_BlazorWebApp/Services/TransitiveTransientDisposableDependency.cs
- 8.0/BlazorSample_WebAssembly/Pages/TransientService.razor
- 8.0/BlazorSample_WebAssembly/Program.cs
- 8.0/BlazorSample_WebAssembly/Services/TransientDisposableService.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31689
> Transient Dependencies

- 3.1/BlazorServerEFCoreSample/Pages/Index.razor
- 5.0/BlazorServerEFCoreSample/Pages/Index.razor
- 6.0/BlazorServerEFCoreSample/Pages/Index.razor
- 7.0/BlazorServerEFCoreSample/Pages/Index.razor
- 8.0/BlazorWebAppEFCore/Components/Pages/Home.razor
Fixes #189
Thanks @andrei-epure-sonarsource! 🚀 ... Quick fix to all of the EFCore sample apps for the bad casing there 😈. That apparently happened because those updates were performed with a set of find-'n-replace operations, and I didn't faithfully set the "replace" of the find-'n-replace correctly.
> Fix bad type casing in EFCore samples

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/SeedData.cs
Let's go with a ***VASTLY COOLER*** test user .......
> Change the test user

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Program.cs
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Routes.razor
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Program.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Routes.razor
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
> Update adoption of cascading auth state

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Backend.csproj
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs
> Add NSwag to WASM+Identity sample

- 3.1/BlazorSample_Server/Pages/index/ReferenceParent2.razor
- 3.1/BlazorSample_WebAssembly/Pages/index/ReferenceParent2.razor
- 5.0/BlazorSample_Server/Pages/index/ReferenceParent2.razor
- 5.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent2.razor
- 6.0/BlazorSample_Server/Pages/index/ReferenceParent2.razor
- 6.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent2.razor
- 7.0/BlazorSample_Server/Pages/index/ReferenceParent2.razor
- 7.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent2.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/ReferenceParent2.razor
- 8.0/BlazorSample_WebAssembly/Pages/ReferenceParent2.razor
> Update ReferenceParent2 component

- 3.1/BlazorSample_Server/Pages/event-handling/EventHandlerExample7.razor
- 3.1/BlazorSample_Server/Pages/index/BlazorRocks1.razor
- 3.1/BlazorSample_Server/Pages/index/BlazorRocks2.razor
- 3.1/BlazorSample_Server/Pages/index/ReferenceParent1.razor
- 3.1/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem2.razor
- 3.1/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample7.razor
- 3.1/BlazorSample_WebAssembly/Pages/index/BlazorRocks1.razor
- 3.1/BlazorSample_WebAssembly/Pages/index/BlazorRocks2.razor
- 3.1/BlazorSample_WebAssembly/Pages/index/ReferenceParent1.razor
- 3.1/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem2.razor
- 5.0/BlazorSample_Server/Pages/event-handling/EventHandlerExample7.razor
- 5.0/BlazorSample_Server/Pages/index/BlazorRocks1.razor
- 5.0/BlazorSample_Server/Pages/index/BlazorRocks2.razor
- 5.0/BlazorSample_Server/Pages/index/ReferenceParent1.razor
- 5.0/BlazorSample_Server/Shared/call-dotnet-from-js/ListItem2.razor
- 5.0/BlazorSample_WebAssembly/Pages/event-handling/EventHandlerExample7.razor
- 5.0/BlazorSample_WebAssembly/Pages/index/BlazorRocks1.razor
- 5.0/BlazorSample_WebAssembly/Pages/index/BlazorRocks2.razor
- 5.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent1.razor
- 5.0/BlazorSample_WebAssembly/Shared/call-dotnet-from-js/ListItem2.razor
- 6.0/BlazorSample_Server/Pages/index/ReferenceParent1.razor
- 6.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent1.razor
- 7.0/BlazorSample_Server/Pages/index/ReferenceParent1.razor
- 7.0/BlazorSample_WebAssembly/Pages/index/ReferenceParent1.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/ReferenceParent1.razor
- 8.0/BlazorSample_WebAssembly/Pages/ReferenceParent1.razor
Addresses #31860
Additional updates, including some sneaky 😈 NRT and 😈 head content control updates.
> Additional example updates

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/TheSunmakers.razor
- 8.0/BlazorSample_WebAssembly/Pages/TheSunmakers.razor
This will be handled via the article text.
> Remove comment from component

- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/BlazorApp.Client.csproj
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Layout/NavMenu.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrNamedClient.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrTypedClient.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Program.cs
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Services/ClientMovieService.cs
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/TodoHttpClient.cs
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31887
> BWA Call web API sample updates

- 6.0/BlazorSample_WebAssembly/wwwroot/index.html
> net6-wasm index.html CSS isolation link fix

- 3.1/BlazorSample_WebAssembly/Program.cs
- 5.0/BlazorSample_WebAssembly/Program.cs
> DetectIncorrectUsageOfTransients cleanup net5 + net3.1

- .github/workflows/dotnet.yml
> Basic CI build

- 3.1/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor
- 3.1/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor
- 5.0/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor
- 5.0/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor
- 6.0/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor
- 6.0/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor
- 7.0/BlazorSample_Server/Pages/synchronization-context/ReceiveNotifications.razor
- 7.0/BlazorSample_WebAssembly/Pages/synchronization-context/ReceiveNotifications.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Notifications.razor
- 8.0/BlazorSample_WebAssembly/Pages/Notifications.razor
> NIT update to notification component UI feedback

- 3.1/BlazorSample_Server/Pages/lifecycle/AfterRender.razor
- 3.1/BlazorSample_WebAssembly/Pages/lifecycle/AfterRender.razor
- 5.0/BlazorSample_Server/Pages/lifecycle/AfterRender.razor
- 5.0/BlazorSample_WebAssembly/Pages/lifecycle/AfterRender.razor
- 6.0/BlazorSample_Server/Pages/lifecycle/AfterRender.razor
- 6.0/BlazorSample_WebAssembly/Pages/lifecycle/AfterRender.razor
- 7.0/BlazorSample_Server/Pages/lifecycle/AfterRender.razor
- 7.0/BlazorSample_WebAssembly/Pages/lifecycle/AfterRender.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/AfterRender.razor
- 8.0/BlazorSample_WebAssembly/Pages/AfterRender.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32117
+ I will add the console output to the lifecycle.md page.
cc @guardrex
> AfterRender.razor simplification

- 3.1/BlazorServerEFCoreSample/Shared/ContactForm.razor
- 5.0/BlazorServerEFCoreSample/Shared/ContactForm.razor
- 6.0/BlazorServerEFCoreSample/Shared/ContactForm.razor
- 7.0/BlazorServerEFCoreSample/Shared/ContactForm.razor
- 8.0/BlazorWebAppEFCore/Components/ContactForm.razor
Fixes #264
Thanks @Phil-mcc! 🚀
> Apply a button type of 'button' to cancel button

- 8.0/BlazorSample_BlazorWebApp/Components/Layout/NavMenu.razor
- 8.0/BlazorSample_WebAssembly/Layout/NavMenu.razor
moved the `TransientService` exclusion to use the same approach as other exclusions
cc @guardrex
> net8 - NavMenu.razor consolidation

- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/App.xaml
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/App.xaml.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/MAUIBlazorWeb.MAUI.csproj
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/MainPage.xaml
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/MainPage.xaml.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/MauiProgram.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Android/MainActivity.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Android/MainApplication.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/MacCatalyst/AppDelegate.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/MacCatalyst/Program.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Tizen/Main.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Tizen/tizen-manifest.xml
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Windows/App.xaml
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Windows/App.xaml.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/Windows/app.manifest
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/iOS/AppDelegate.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/Platforms/iOS/Program.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.MAUI/wwwroot/index.html
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Shared/Components/Layout/NavMenu.razor
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Shared/_Imports.razor
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Web/Components/App.razor
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Web/Components/_Imports.razor
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Web/MAUIBlazorWeb.Web.csproj
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.Web/Program.cs
- 8.0/MAUIBlazorWeb/MAUIBlazorWeb.sln
- 8.0/MauiBlazorWeb/MauiBlazorWeb.Maui/Services/FormFactor.cs
- 8.0/MauiBlazorWeb/MauiBlazorWeb.Shared/Components/Pages/DeviceFormFactor.razor
- 8.0/MauiBlazorWeb/MauiBlazorWeb.Shared/InteractiveRenderSettings.cs
- 8.0/MauiBlazorWeb/MauiBlazorWeb.Shared/Interfaces/IFormFactor.cs
- 8.0/MauiBlazorWeb/MauiBlazorWeb.Web/Services/FormFactor.cs
cc: @BethMassi ... Making a bunch of NIT updates and adding the form factor code. You don't need to look at this at this time. It can all be reviewed when I'm done and the docs PR with the article goes up for review.
> MAUI + BWA sample updates

- 8.0/MauiBlazorWeb/MauiBlazorWeb.Shared/InteractiveRenderSettings.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/29880
> Break long lines in InteractiveRenderSettings

- 8.0/MauiBlazorWeb/README.md
> Add README file

- README.md
> Add article cross-link to README

- 3.1/BlazorSample_Server/Pages/data-binding/Parent3.razor
- 3.1/BlazorSample_Server/Shared/data-binding/ChildParameterExpression.razor
- 3.1/BlazorSample_WebAssembly/Pages/data-binding/Parent3.razor
- 3.1/BlazorSample_WebAssembly/Shared/data-binding/ChildParameterExpression.razor
- 5.0/BlazorSample_Server/Pages/data-binding/Parent3.razor
- 5.0/BlazorSample_Server/Shared/data-binding/ChildParameterExpression.razor
- 5.0/BlazorSample_WebAssembly/Pages/data-binding/Parent3.razor
- 5.0/BlazorSample_WebAssembly/Shared/data-binding/ChildParameterExpression.razor
- 6.0/BlazorSample_Server/Pages/data-binding/Parent3.razor
- 6.0/BlazorSample_Server/Shared/data-binding/ChildParameterExpression.razor
- 6.0/BlazorSample_WebAssembly/Pages/data-binding/Parent3.razor
- 6.0/BlazorSample_WebAssembly/Shared/data-binding/ChildParameterExpression.razor
- 7.0/BlazorSample_Server/Pages/data-binding/Parent3.razor
- 7.0/BlazorSample_Server/Shared/data-binding/ChildParameterExpression.razor
- 7.0/BlazorSample_WebAssembly/Pages/data-binding/Parent3.razor
- 7.0/BlazorSample_WebAssembly/Shared/data-binding/ChildParameterExpression.razor
- 8.0/BlazorSample_BlazorWebApp/Components/ChildParameterExpression.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Parent3.razor
- 8.0/BlazorSample_WebAssembly/Pages/Parent3.razor
- 8.0/BlazorSample_WebAssembly/Shared/ChildParameterExpression.razor
Addresses #30656
This is a *QUICK* example 🏃‍♂️ that we'll probably change later, likely to something more *real world-ish* without actually creating a custom validator component. I just need to get an example surfaced now to cover the scenario.
> Add quick param expression tree convention example

- 8.0/BlazorWebAppOidcBff/MinimalApiJwt/Properties/launchSettings.json
Fixes  #294
Thanks @candritzky! 🚀 ... It think it was updated at some point, but it got by me here in this file :smiling_imp:.
> Update launchUrl in launch settings file

- 8.0/BlazorWebAppOidcBff/Aspire/Aspire.AppHost/Aspire.AppHost.csproj
- 8.0/BlazorWebAppOidcBff/Aspire/Aspire.AppHost/Properties/launchSettings.json
- 8.0/BlazorWebAppOidcBff/Aspire/Aspire.ServiceDefaults/Aspire.ServiceDefaults.csproj
- 8.0/BlazorWebAppOidcBff/Aspire/Aspire.ServiceDefaults/Extensions.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/BlazorWebAppOidc.csproj
Upgraded the BlazorWebAppOidcBff project to Aspire Preview 7
> Updated BlazorWebAppOidcBff to Aspire 8.0.1

- 8.0/BlazorWebAppMovies/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32359
> Add a README file to BWA Movies dB sample app

- 8.0/BlazorWebAppMovies/Components/App.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Create.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Delete.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Details.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Edit.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Index.razor
- 8.0/BlazorWebAppMovies/Data/SeedData.cs
- 8.0/BlazorWebAppMovies/Models/Movie.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32359
> Movie tutorial sample updates

- 8.0/BlazorWebAppMovies/.config/dotnet-tools.json
- 8.0/BlazorWebAppMovies/Components/App.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Delete.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Details.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Index.razor
- 8.0/BlazorWebAppMovies/Components/Pages/Weather.razor
- 8.0/BlazorWebAppMovies/Data/SeedData.cs
- 8.0/BlazorWebAppMovies/Migrations/20240514105534_InitialCreate.cs
- 8.0/BlazorWebAppMovies/Migrations/BlazorWebAppMoviesContextModelSnapshot.cs
- 8.0/BlazorWebAppMovies/Models/Movie.cs
- 8.0/BlazorWebAppMovies/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/32747
> BWA tutorial samp updates

- 8.0/BlazorWebAppMovies/BlazorWebAppMovies.csproj
Addresses https://github.com/dotnet/AspNetCore.Docs/pull/32747
> BWA tutorial sample updates

- 8.0/BlazorSample_BlazorWebApp/Components/Layout/MainLayout.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/EmptyContent.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Parameter2.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/PromotionGrid.razor
- 8.0/BlazorSample_BlazorWebApp/Components/ParameterChild.razor
- 8.0/BlazorSample_WebAssembly/Pages/VirtualizedTable.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33051
> Update component param values

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32512
> Update role claim type and remark

- 8.0/WASMBrowserAppImportExportInterop/DateInterop.cs
- 8.0/WASMBrowserAppImportExportInterop/EventsInterop.cs
- 8.0/WASMBrowserAppImportExportInterop/JSObjectBenchmark.cs
- 8.0/WASMBrowserAppImportExportInterop/JSObjectInterop.cs
- 8.0/WASMBrowserAppImportExportInterop/PrimativesShimInterop.cs
- 8.0/WASMBrowserAppImportExportInterop/Program.cs
- 8.0/WASMBrowserAppImportExportInterop/PromisesInterop.cs
- 8.0/WASMBrowserAppImportExportInterop/Properties/AssemblyInfo.cs
- 8.0/WASMBrowserAppImportExportInterop/Properties/launchSettings.json
- 8.0/WASMBrowserAppImportExportInterop/README.md
- 8.0/WASMBrowserAppImportExportInterop/WASMBrowserApp.csproj
- 8.0/WASMBrowserAppImportExportInterop/WASMBrowserApp.sln
- 8.0/WASMBrowserAppImportExportInterop/runtimeconfig.template.json
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/DateShim.js
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/EventsShim.js
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/JSObjectShim.js
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/PrimitivesShim.js
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/PromisesShim.js
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/index.html
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32001
> Add Import-Export JS interop sample app

- 8.0/WASMBrowserAppImportExportInterop/wwwroot/index.html
- 8.0/WASMBrowserAppImportExportInterop/wwwroot/main.js
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32001
> JS Import-Export sample updates

- 5.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 5.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 6.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 6.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 7.0/BlazorSample_Server/Pages/file-uploads/FileUpload2.razor
- 7.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload2.razor
- 8.0/BlazorSample_WebAssembly/Pages/FileUpload2.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33272
> Update FileUpload2 component code

- 5.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 6.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 7.0/BlazorSample_WebAssembly/Pages/file-uploads/FileUpload2.razor
- 8.0/BlazorSample_WebAssembly/Pages/FileUpload2.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33272
> Revert file upload changes to WASM file upload components

- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Create.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Delete.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Details.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Edit.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Index.razor
- 8.0/BlazorWebAppMovies/Data/BlazorWebAppMoviesContext.cs
- 8.0/BlazorWebAppMovies/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issue/32359
> Tutorial sample app updates

- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Create.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Delete.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Details.razor
- 8.0/BlazorWebAppMovies/Components/Pages/MoviePages/Edit.razor
- 8.0/BlazorWebAppMovies/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/32359
> Tutorial sample updates

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload2.razor
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Pages/UserClaims.razor
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc.Client/Pages/UserClaims.razor
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/PrivateEditorPage.razor
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/PrivateManagerPage.razor
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/PrivatePage.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33474
> Swap `.Any()` for `.Count()`

- 8.0/BlazorWebAppEFCore/BlazorWebAppEFCore.csproj
- 8.0/BlazorWebAppEFCore/Data/ContactContext.cs
- 8.0/BlazorWebAppEFCore/Data/SeedContacts.cs
- 8.0/BlazorWebAppEFCore/DatabaseUtility.cs
- 8.0/BlazorWebAppEFCore/Grid/GridControls.cs
- 8.0/BlazorWebAppEFCore/Grid/GridQueryAdapter.cs
- 8.0/BlazorWebAppEFCore/Program.cs
the existing .SLN raises Warnings/Messages and analyzers encourage modernizing changes.
This PR offers cleaner code, so I hope MS owners will accept these changes as-is
but **Allow edits by maintainers** checkbox set to allow tweaking
> modernize per analyzers

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/CallDotnet1.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/CallDotnet8.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallDotnet1.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallDotnet8.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33780
> Code example update

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/BlazorWebAppEntra.http
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/33779
> Add HTTP file to BWA+Entra sample app

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/BlazorWebAppEntra.csproj
We'll be guiding devs to initialize the app from the article. That way, they'll get a unique value.
Similar changes will take place for the OIDC samples separately in a bit.
> Drop user secrets Id

- 9.0/BlazorSignalRApp/README.md
- 9.0/BlazorWebAppEFCore/README.md
- 9.0/BlazorWebAppEntra/README.md
- 9.0/BlazorWebAssemblyScopesLogger/README.md
- 9.0/WASMBrowserAppImportExportInterop/README.md
- README.md
Updates the list but also adds article links to existing README files and adds a couple of README files with cross-links to articles.
> Update sample list in README

- 5.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample6.razor
- 5.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor
- 6.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample6.razor
- 6.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor
- 7.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample6.razor
- 7.0/BlazorSample_WebAssembly/Pages/call-js-from-dotnet/CallJsExample8.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallDotnet1.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallDotnet8.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallJs6.razor
- 8.0/BlazorSample_WebAssembly/Pages/CallJs8.razor
- 8.0/BlazorSample_WebAssembly/Shared/ListItem2.razor
- 9.0/BlazorSample_WebAssembly/Pages/CallDotnet1.razor
- 9.0/BlazorSample_WebAssembly/Pages/CallDotnet8.razor
- 9.0/BlazorSample_WebAssembly/Pages/CallJs6.razor
- 9.0/BlazorSample_WebAssembly/Pages/CallJs8.razor
- 9.0/BlazorSample_WebAssembly/Shared/ListItem2.razor
Fixes https://github.com/dotnet/blazor-samples/pull/396#issuecomment-2485018609
> Drop JSDisconnectedException trap from WASM samples

- 3.1/BlazorSample_Server/TimerService.cs
- 3.1/BlazorSample_WebAssembly/TimerService.cs
- 5.0/BlazorSample_Server/TimerService.cs
- 5.0/BlazorSample_WebAssembly/TimerService.cs
- 6.0/BlazorSample_Server/TimerService.cs
- 6.0/BlazorSample_WebAssembly/TimerService.cs
- 7.0/BlazorSample_Server/TimerService.cs
- 7.0/BlazorSample_WebAssembly/TimerService.cs
- 8.0/BlazorSample_BlazorWebApp/Components/ListItem2.razor
- 8.0/BlazorSample_WebAssembly/Shared/ListItem2.razor
- 9.0/BlazorSample_BlazorWebApp/Components/ListItem2.razor
- 9.0/BlazorSample_WebAssembly/Shared/ListItem2.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34360
> async void updates

- README.md
> Add git sparse-checkout procedure

- 9.0/BlazorWebAppMovies/Components/Pages/Weather.razor
Although the update wasn't backported in project templates (it's a 10.0 update), let's just go ahead and make this update to the sample. I'd like to proactively avoid one or more issues on it.
> Fix misspelled word

- .github/workflows/static.yml
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34107
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34461
> Update static workflow

- BlazorWebAssemblyXrefGenerator/Pages/Home.razor
- BlazorWebAssemblyXrefGenerator/Shared/ApiResult.razor
- BlazorWebAssemblyXrefGenerator/_Imports.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34107
> Update Xref Gen Tool

- 9.0/WASMBrowserAppImportExportInterop/DateInterop.cs
- 9.0/WASMBrowserAppImportExportInterop/EventsInterop.cs
- 9.0/WASMBrowserAppImportExportInterop/JSObjectBenchmark.cs
- 9.0/WASMBrowserAppImportExportInterop/JSObjectInterop.cs
- 9.0/WASMBrowserAppImportExportInterop/PrimitivesInterop.cs
- 9.0/WASMBrowserAppImportExportInterop/Program.cs
- 9.0/WASMBrowserAppImportExportInterop/PromisesInterop.cs
Fixes #450
Maraf, Pavel ... Can I take VS IntelliSense's advice to use a pair of local functions (see the DIFF)?
I also apply a namespace to resolve that IntelliSense complaint.
Note that none of the affected code is shown in the article, so we don't need to sweat article updates for this.
> WASMBrowserApp code updates

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/EmptyContent.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload1.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload2.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload3.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Starship5.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Starship9.razor
- 8.0/BlazorSample_BlazorWebApp/Components/Pages/Todo.razor
- 8.0/BlazorSample_WebAssembly/Pages/EmptyContent.razor
- 8.0/BlazorSample_WebAssembly/Pages/FileUpload1.razor
- 8.0/BlazorSample_WebAssembly/Pages/FileUpload2.razor
- 8.0/BlazorSample_WebAssembly/Pages/Starship5.razor
- 8.0/BlazorSample_WebAssembly/Pages/Starship9.razor
- 8.0/BlazorSample_WebAssembly/Pages/Todo.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/EmptyContent.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload1.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload2.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/FileUpload3.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/Starship5.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/Starship9.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/Todo.razor
- 9.0/BlazorSample_WebAssembly/Pages/EmptyContent.razor
- 9.0/BlazorSample_WebAssembly/Pages/FileUpload1.razor
- 9.0/BlazorSample_WebAssembly/Pages/FileUpload2.razor
- 9.0/BlazorSample_WebAssembly/Pages/Starship5.razor
- 9.0/BlazorSample_WebAssembly/Pages/Starship9.razor
- 9.0/BlazorSample_WebAssembly/Pages/Todo.razor
- 9.0/BlazorSample_WebAssembly/Ship.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34530
> Code updates for collection simplification

- .github/workflows/validate-samples.yml
Fixes #243
@hakenr ... How about this? Looks good from here.
I'll come back at a later date and add more samples to this.
I'll perform a 9.0 SDK test with the 3.1 Blazor Server and Blazor WebAssembly apps right after this goes in to confirm it works.
> Build sample apps automation

- README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34939
> Add MAUI+BWA+Identity to sample list

- 9.0/MauiBlazorWebIdentity/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34939
> Patch README sample title and article title

- README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34939
> Patch repo README

- .github/workflows/static.yml
- .github/workflows/validate-samples.yml
Fixes #491
Updating these will be tracked by the annual docs release tracking issue.
🤔 I'm not sure about checking and updating more frequently than one year in order to capture bug fixes for the actions.  I'll discuss it with Dan and Larry offline.
> Pin GH Actions to SHAs

- 9.0/BlazorWebAppWinAuthServer/Components/ForceLogin.razor
- 9.0/BlazorWebAppWinAuthServer/Components/Layout/NavMenu.razor
- 9.0/BlazorWebAppWinAuthServer/Components/Pages/UserClaims.razor
- 9.0/BlazorWebAppWinAuthServer/Components/Pages/Weather.razor
- 9.0/BlazorWebAppWinAuthServer/Components/Routes.razor
- 9.0/BlazorWebAppWinAuthServer/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/34707
> Update BWA+WinAuth sample

- 8.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter2.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallMovieWebApiAuto.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallMovieWebApiCsr.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiAuto.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsr.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrNamedClient.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrPatch.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrTypedClient.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Components/Pages/CallMovieWebApiSsr.razor
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Components/Pages/CallTodoWebApiSsr.razor
- 8.0/BlazorWebAppCallWebApi_Weather/BlazorApp.Client/Pages/Weather.razor
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Pages/Weather.razor
- 9.0/BlazorSample_BlazorWebApp/Components/Pages/PrerenderedCounter2.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallMovieWebApiAuto.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallMovieWebApiCsr.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiAuto.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsr.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrNamedClient.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrPatch.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp.Client/Pages/CallTodoWebApiCsrTypedClient.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Components/Pages/CallMovieWebApiSsr.razor
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Components/Pages/CallTodoWebApiSsr.razor
- 9.0/BlazorWebAppCallWebApi_Weather/BlazorApp.Client/Pages/Weather.razor
- 9.0/BlazorWebAppEntra/BlazorWebAppEntra.Client/Pages/Weather.razor
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc.Client/Pages/Weather.razor
Fixes #503
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35115
> Move call to `RegisterOnPersisting` to the end

- BlazorWebAssemblyXrefGenerator/Pages/Home.razor
- BlazorWebAssemblyXrefGenerator/Program.cs
From the back of #505 
- Reverted the changes around `ProxyClient` to previous
- Removed unused registered `APIBrowserPageClient`
> Improvements to Xref Generator

- BlazorWebAssemblyXrefGenerator/README.md
> Update article cross-link

- 8.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppEntraBff/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
Found a bug to squash 😈, and I'd like to uncomment the options config for the authority and audience.
> Update MinimalApiJwt projects

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Weather/ServerWeatherForecaster.cs
- 8.0/BlazorWebAppOidc/README.md
- 8.0/BlazorWebAppOidcBff/README.md
- 8.0/BlazorWebAppOidcServer/README.md
- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Weather/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppEntraBff/Aspire/Aspire.AppHost/Aspire.AppHost.csproj
- 9.0/BlazorWebAppEntraBff/Aspire/Aspire.ServiceDefaults/Aspire.ServiceDefaults.csproj
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra.Client/BlazorWebAppEntra.Client.csproj
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/BlazorWebAppEntra.csproj
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/appsettings.json
- 9.0/BlazorWebAppEntraBff/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppEntraBff/README.md
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/Weather/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppOidc/README.md
- 9.0/BlazorWebAppOidcBff/README.md
- 9.0/BlazorWebAppOidcServer/README.md
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31691
> MS Id Web Downstream API package for Entra+BFF

- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/appsettings.json
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31691
> Update BWA+Entra app settings

- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
- 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31691
> Update BWA+OIDC BFF app config

- 9.0/MauiBlazorWebIdentity/MauiBlazorWeb/MauiBlazorWeb/MauiProgram.cs
Fixes #521
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35310
> Update service registration

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Weather/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/Weather/ServerWeatherForecaster.cs
> Missing "class" on two `ServerWeatherForecaster` classes

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/CookieOidcServiceCollectionExtensions.cs
- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/CookieOidcServiceCollectionExtensions.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
- 8.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/CookieOidcServiceCollectionExtensions.cs
- 8.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/Program.cs
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/CookieOidcServiceCollectionExtensions.cs
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc/CookieOidcServiceCollectionExtensions.cs
- 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
- 9.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/CookieOidcServiceCollectionExtensions.cs
- 9.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/Program.cs
> Remove word 'refresh' from method name

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/Program.cs
- 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc/Program.cs
> Serialize all claims for auth state serialization

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
- 9.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
Fixes #517
Thanks @nicholasyin! 🚀 ... I'll trap and swallow the unauthorized exception for a by-design behavior.
> Trap and swallow unauthorized exception

- 8.0/BlazorWebAppOidc/MinimalApiJwt/MinimalApiJwt.csproj
- 8.0/BlazorWebAppOidc/MinimalApiJwt/Program.cs
- 8.0/BlazorWebAppOidc/MinimalApiJwt/Properties/launchSettings.json
- 8.0/BlazorWebAppOidcBff/MinimalApiJwt/MinimalApiJwt.csproj
- 8.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
- 8.0/BlazorWebAppOidcBff/MinimalApiJwt/Properties/launchSettings.json
- 8.0/BlazorWebAppOidcServer/MinimalApiJwt/MinimalApiJwt.csproj
- 8.0/BlazorWebAppOidcServer/MinimalApiJwt/Program.cs
- 8.0/BlazorWebAppOidcServer/MinimalApiJwt/Properties/launchSettings.json
- 9.0/BlazorWebAppEntra/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppEntra/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppEntra/MinimalApiJwt/Properties/launchSettings.json
- 9.0/BlazorWebAppEntraBff/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppEntraBff/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppEntraBff/MinimalApiJwt/Properties/launchSettings.json
- 9.0/BlazorWebAppOidc/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppOidc/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppOidc/MinimalApiJwt/Properties/launchSettings.json
- 9.0/BlazorWebAppOidcBff/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppOidcBff/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppOidcBff/MinimalApiJwt/Properties/launchSettings.json
- 9.0/BlazorWebAppOidcServer/MinimalApiJwt/MinimalApiJwt.csproj
- 9.0/BlazorWebAppOidcServer/MinimalApiJwt/Program.cs
- 9.0/BlazorWebAppOidcServer/MinimalApiJwt/Properties/launchSettings.json
> Add OpenAPI/SwaggerUI

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc.sln
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc.sln
Fixes #540
Thanks @skywalkerisnull! ... I found one more 😈 in another solution. The rest look ok. This will update these solutions immediately.
> Fix solutions

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/BlazorWebAppEntra.csproj
- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/BlazorWebAppEntra.csproj
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35506
> BWA+Entra sample app updates

- 8.0/BlazorWebAppOidc/BlazorWebAppOidc/Weather/ServerWeatherForecaster.cs
- 8.0/BlazorWebAppOidcBff/BlazorWebAppOidc/ServerWeatherForecaster.cs
- 8.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/Components/Pages/Weather.razor
- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Components/Pages/DataProcessing.razor
- 9.0/BlazorWebAppOidc/BlazorWebAppOidc/Weather/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppOidcBff/BlazorWebAppOidc/ServerWeatherForecaster.cs
- 9.0/BlazorWebAppOidcServer/BlazorWebAppOidcServer/Components/Pages/Weather.razor
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/31691
> Apply `using`

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35586
> Add Managed Identity code/comments

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35586
> Add one more app name for DP config

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35586
A few more updates!
> Additional Managed Identity updates

- 9.0/BlazorWebAppEntra/BlazorWebAppEntra/Program.cs
- 9.0/BlazorWebAppEntraBff/BlazorWebAppEntra/Program.cs
Addresses https://github.com/dotnet/AspNetCore.Docs/issues/35665
> Azure credential options for VS to BWA+Entra samps

- 9.0/MauiBlazorWebIdentity/MauiBlazorWeb/MauiBlazorWeb.Web/Program.cs
Reverts dotnet/blazor-samples#562
> Revert "Update Swashbuckle link"

- 8.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
- 9.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Backend.csproj
- 9.0/BlazorWebAssemblyStandaloneWithIdentity/Backend/Program.cs
- 9.0/BlazorWebAssemblyStandaloneWithIdentity/BlazorWasmAuth/Identity/CookieAuthenticationStateProvider.cs
Addresses https://github.com/dotnet/blazor-samples/issues/564
> Remove Nswag/Swagger

- 10.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Program.cs
- 8.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Program.cs
- 9.0/BlazorWebAppCallWebApi/BlazorApp/BlazorApp/Program.cs
Fixes #476
Thanks @davisnw! 🚀 ... Sorry that it took so long to reach this. We've been *very busy* this year! ⛰️⛏️😅 
This will use the injected implementation for `IMovieService` to create, update, and delete movies to avoid code duplication. I checked the article, and no changes are needed there. I'm updating all three versions of the sample ... 8, 9, and 10.
> Remove code duplication
